# ICMD Configuration File
dataset_params:
  root_dir: /home/ysz/datasets/ted384-png
  frame_shape: [768,768]
  id_sampling: True
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1

model_params:
  num_feature: 20
  num_regions: 40
  num_background: 5
  feature_size: 96
  num_channels: 3
  region_predictor_params:
    block_expansion: 32
    max_features: 1024
    num_blocks: 5
    pad: 3
  generator_params:
    block_expansion: 64
    max_features: 512
    num_bottleneck_blocks: 6
    multiRes_mode: 3 # 1: s, 2: s+0.5s, 3: s+0.5s+0.25s
    pixelwise_flow_predictor_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      use_deformed_source: True
      estimate_occlusion_map: True


train_params:
  num_epochs: 100
  num_repeats: 150
  epoch_milestones: [60, 90]
  lr: 2.0e-4
  multiRes_mode: 3
  batch_size: 12
  dataloader_workers: 8
  checkpoint_freq: 1
  scales: [1, 0.5, 0.25, 0.125]
  loss_weights:
    perceptual: [10, 10, 10, 10, 10]
    pixel: 10
    bg: 10

visualizer_params:
  kp_size: 5
  draw_border: True
  colormap: 'gist_rainbow'
  region_bg_color: [1, 1, 1]